var memorizeColors = {
  ["czerwony"]: "#E42828",
  ["fioletowy"]: "#C92EFF",
  ["zielony"]: "#8FFF00",
};

var randomColors = ["#E42828", "#C92EFF", "#8FFF00"];

var memorizeIcons = [
  "fa-solid fa-server",
  "fa-solid fa-download",
  "fa-solid fa-bomb",
  "fa-solid fa-file",
  "fa-solid fa-star",
  "fa-solid fa-house",
  "fa-solid fa-magnifying-glass",
  "fa-solid fa-image",
  "fa-solid fa-phone",
  "fa-solid fa-envelope",
  "fa-solid fa-location-dot",
  "fa-solid fa-cloud",
  "fa-solid fa-filter",
  "fa-solid fa-mug-hot",
  "fa-solid fa-umbrella",
  "fa-solid fa-gear",
  "fa-solid fa-camera",
  "fa-solid fa-tag",
  "fa-solid fa-book",
  "fa-solid fa-bookmark",
  "fa-solid fa-droplet",
  "fa-solid fa-share",
  "fa-solid fa-fire",
  "fa-solid fa-eye",
  "fa-solid fa-magnet",
  "fa-solid fa-hand",
  "fa-solid fa-key",
  "fa-solid fa-thumbtack",
  "fa-solid fa-paper-plane",
  "fa-solid fa-code",
  "fa-solid fa-globe",
  "fa-solid fa-truck",
  "fa-solid fa-city",
  "fa-solid fa-ticket",
  "fa-solid fa-tree",
  "fa-solid fa-flask",
  "fa-solid fa-briefcase",
  "fa-solid fa-compass",
  "fa-solid fa-bath",
  "fa-solid fa-handshake",
  "fa-solid fa-binoculars",
  "fa-solid fa-palette",
  "fa-solid fa-shop",
  "fa-solid fa-bug",
  "fa-solid fa-fish",
  "fa-solid fa-link",
];
